In [9]:
# ==========================================================
# EXPERIMENT NO.1
# Introduction to Kaggle and Data Preprocessing
# ==========================================================

# STEP 1 : Import Libraries

import os
import pandas as pd
import numpy as np
import kagglehub

from IPython.display import display
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# ==========================================================
# STEP 2 : Import Dataset
# ==========================================================

path = kagglehub.dataset_download("brendan45774/test-file")

csv_file = os.path.join(path, "tested.csv")

df = pd.read_csv(csv_file)

# ==========================================================
# DATASET
# ==========================================================

print("=" * 80)
print("DATASET")
print("=" * 80)

display(df)

print("\nDataset Shape :", df.shape)

# ==========================================================
# NULL VALUES BEFORE PREPROCESSING
# ==========================================================

print("\n")
print("=" * 80)
print("NULL VALUES")
print("=" * 80)

null_values = pd.DataFrame({
    "Column Name": df.columns,
    "Missing Values": df.isnull().sum().values
})

display(null_values)

# ==========================================================
# STEP 3 : Handle Missing Values
# ==========================================================

df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Fare"] = df["Fare"].fillna(df["Fare"].mean())

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

df.drop("Cabin", axis=1, inplace=True)

print("\n")
print("=" * 80)
print("NULL VALUES AFTER PREPROCESSING")
print("=" * 80)

null_after = pd.DataFrame({
    "Column Name": df.columns,
    "Missing Values": df.isnull().sum().values
})

display(null_after)

# ==========================================================
# STEP 4 : Encode Categorical Data
# ==========================================================

encoder = LabelEncoder()

df["Sex"] = encoder.fit_transform(df["Sex"])

df["Embarked"] = encoder.fit_transform(df["Embarked"])

# ==========================================================
# Remove Unnecessary Columns
# ==========================================================

df.drop(["PassengerId", "Name", "Ticket"], axis=1, inplace=True)

# ==========================================================
# STEP 5 : Normalize Data
# ==========================================================

scaler = StandardScaler()

df[["Age", "Fare"]] = scaler.fit_transform(df[["Age", "Fare"]])

print("\n")
print("=" * 80)
print("NORMALIZED DATA")
print("=" * 80)

display(df)

# ==========================================================
# STEP 6 : Split Dataset
# ==========================================================

X = df.drop("Survived", axis=1)

y = df["Survived"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\n")
print("=" * 80)
print("DATA SPLITTING")
print("=" * 80)

split_table = pd.DataFrame({
    "Dataset": ["Training", "Testing"],
    "Feature Shape": [X_train.shape, X_test.shape],
    "Label Shape": [y_train.shape, y_test.shape]
})

display(split_table)

# ==========================================================
# TRAIN DATA
# ==========================================================

print("\n")
print("=" * 80)
print("TRAIN DATA")
print("=" * 80)

display(X_train)

print("\nTraining Labels")

display(y_train.to_frame(name="Survived"))

# ==========================================================
# TEST DATA
# ==========================================================

print("\n")
print("=" * 80)
print("TEST DATA")
print("=" * 80)

display(X_test)

print("\nTesting Labels")

display(y_test.to_frame(name="Survived"))

# ==========================================================
# FINAL DATASET
# ==========================================================

print("\n")
print("=" * 80)
print("FINAL PREPROCESSED DATASET")
print("=" * 80)

display(df)

print("\nExperiment Completed Successfully.")

Using Colab cache for faster access to the 'test-file' dataset.
================================================================================
DATASET
================================================================================

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Dataset Shape : (418, 12)


================================================================================
NULL VALUES
================================================================================

    Column Name  Missing Values
0   PassengerId               0
1      Survived               0
2        Pclass               0
3          Name               0
4           Sex               0
5           Age              86
6         SibSp               0
7         Parch               0
8        Ticket               0
9          Fare               1
10        Cabin             327
11     Embarked               0

================================================================================
NULL VALUES AFTER PREPROCESSING
================================================================================

    Column Name  Missing Values
0   PassengerId               0
1      Survived               0
2        Pclass               0
3          Name               0
4           Sex               0
5           Age               0
6         SibSp               0
7         Parch               0
8        Ticket               0
9          Fare               0
10     Embarked               0

================================================================================
NORMALIZED DATA
================================================================================

     Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0           0       3    1  0.334993      0      0 -0.498407         1
1           1       3    0  1.325530      1      0 -0.513274         2
2           0       2    1  2.514175      0      0 -0.465088         1
3           0       3    1 -0.259330      0      0 -0.483466         2
4           1       3    0 -0.655545      1      1 -0.418471         2
..        ...     ...  ...       ...    ...    ...       ...       ...
413         0       3    1  0.000000      0      0 -0.494448         2
414         1       1    0  0.691586      0      0  1.313753         0
415         0       3    1  0.651965      0      0 -0.508792         2
416         0       3    1  0.000000      0      0 -0.494448         2
417         0       3    1  0.000000      1      1 -0.237906         0

[418 rows x 8 columns]

================================================================================
DATA SPLITTING
================================================================================

    Dataset Feature Shape Label Shape
0  Training      (334, 7)      (334,)
1   Testing       (84, 7)       (84,)

================================================================================
TRAIN DATA
================================================================================

     Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
336       2    1  0.136885      0      0 -0.405697         2
31        2    1 -0.497059      2      0 -0.073999         2
84        2    1  0.000000      0      0 -0.446786         1
287       1    1 -0.497059      1      0  0.836228         2
317       2    1 -0.893274      0      0 -0.450521         2
..      ...  ...       ...    ...    ...       ...       ...
71        3    1 -0.734788      0      0 -0.497213         2
106       3    1 -0.734788      0      0 -0.498558         1
270       1    1  1.246287      0      0  0.710273         0
348       2    1 -0.497059      0      0 -0.396732         2
102       3    1  0.000000      0      0 -0.499827         1

[334 rows x 7 columns]

Training Labels

     Survived
336         0
31          0
84          0
287         0
317         0
..        ...
71          0
106         0
270         0
348         0
102         0

[334 rows x 1 columns]

================================================================================
TEST DATA
================================================================================

     Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
321       3    1 -0.417816      0      0 -0.509165         0
324       1    0  0.691586      0      0  3.150417         2
388       3    1 -0.734788      0      0 -0.499827         1
56        3    1  0.374614      0      0 -0.497213         2
153       3    0  0.453857      0      2 -0.420340         2
..      ...  ...       ...    ...    ...       ...       ...
57        3    1 -0.417816      0      0 -0.501620         2
126       3    1 -0.655545      0      0 -0.499006         2
24        1    0  1.404773      1      3  4.065500         0
17        3    1 -0.734788      0      0 -0.509240         0
66        3    0 -0.972517      0      0 -0.497511         1

[84 rows x 7 columns]

Testing Labels

     Survived
321         0
324         1
388         0
56          0
153         1
..        ...
57          0
126         0
24          1
17          0
66          1

[84 rows x 1 columns]

================================================================================
FINAL PREPROCESSED DATASET
================================================================================

     Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0           0       3    1  0.334993      0      0 -0.498407         1
1           1       3    0  1.325530      1      0 -0.513274         2
2           0       2    1  2.514175      0      0 -0.465088         1
3           0       3    1 -0.259330      0      0 -0.483466         2
4           1       3    0 -0.655545      1      1 -0.418471         2
..        ...     ...  ...       ...    ...    ...       ...       ...
413         0       3    1  0.000000      0      0 -0.494448         2
414         1       1    0  0.691586      0      0  1.313753         0
415         0       3    1  0.651965      0      0 -0.508792         2
416         0       3    1  0.000000      0      0 -0.494448         2
417         0       3    1  0.000000      1      1 -0.237906         0

[418 rows x 8 columns]

Experiment Completed Successfully.